"""Add non-nullable  text column to persist user answers for exercises

Revision ID: 3ebb198c91e4
Revises: f4962d68824f
Create Date: 2025-12-26 21:11:32.413120

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3ebb198c91e4'
down_revision: Union[str, Sequence[str], None] = 'f4962d68824f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_exercise_history', sa.Column('user_answer', sa.Text(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_exercise_history', 'user_answer')
    # ### end Alembic commands ###
