"""Fix foreign key (user_fk) cascade constraints

Revision ID: 860522b56861
Revises: e9d426e6d045
Create Date: 2026-01-11 19:41:37.866991

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '860522b56861'
down_revision = 'e9d426e6d045'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('user_exercise_history_user_id_fkey'), 'user_exercise_history', type_='foreignkey')
    op.create_foreign_key(None, 'user_exercise_history', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('user_level_languages_user_id_fkey'), 'user_level_languages', type_='foreignkey')
    op.create_foreign_key(None, 'user_level_languages', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_level_languages', type_='foreignkey')
    op.create_foreign_key(op.f('user_level_languages_user_id_fkey'), 'user_level_languages', 'users', ['user_id'], ['id'])
    op.drop_constraint(None, 'user_exercise_history', type_='foreignkey')
    op.create_foreign_key(op.f('user_exercise_history_user_id_fkey'), 'user_exercise_history', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###