"""empty message

Revision ID: 99a19fb9275f
Revises: 
Create Date: 2025-12-15 17:39:52.622213

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '99a19fb9275f'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('exercises',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False, comment='Surrogate key of the table'),
    sa.Column('topic', sa.String(length=100), nullable=False),
    sa.Column('difficult_level', sa.Enum('A1', 'A2', 'B1', 'B2', 'C1', 'C2', name='language_level'), nullable=False, comment='CEFR Language levels'),
    sa.Column('type', sa.Enum('multiple_choice', 'sentence_translation', name='exercise_type'), nullable=False),
    sa.Column('options', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('question_text', sa.Text(), nullable=False),
    sa.Column('question_language', sa.Enum('UK', 'EN', 'DE', name='language'), nullable=False, comment='Language code in ISO 639-1" format'),
    sa.Column('correct_answer', sa.Text(), nullable=False),
    sa.Column('answer_language', sa.Enum('UK', 'EN', 'DE', name='language'), nullable=False, comment='Language code in ISO 639-1" format'),
    sa.Column('correct_answer_translation', sa.Text(), nullable=True),
    sa.Column('answer_translation_language', sa.Enum('UK', 'EN', 'DE', name='language'), nullable=True, comment='Language code in ISO 639-1" format'),
    sa.Column('added_at', sa.DateTime(timezone=True), server_default=sa.text("TIMEZONE('utc', now())"), nullable=False, comment='Record creation date and time'),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_exercises_active_topic_level', 'exercises', ['topic', 'difficult_level'], unique=False, postgresql_where=sa.text('is_active=true'))
    op.create_table('users',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False, comment='Surrogate key of the table'),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('native_language', sa.Enum('UK', 'EN', 'DE', name='language'), nullable=False, comment='Language code in ISO 639-1" format'),
    sa.Column('hashed_password', sa.Text(), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text("TIMEZONE('utc', now())"), nullable=False, comment='Record creation date and time'),
    sa.CheckConstraint("email ~ '^[A-Za-z0-9._%%+-]+@[A-Za-z0-9.-]+\\.[A-Za-z]{2,}$'", name='check_email_format'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('user_exercise_history',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False, comment='Surrogate key of the table'),
    sa.Column('user_id', sa.BigInteger(), nullable=False, comment='Reference to user'),
    sa.Column('exercise_id', sa.BigInteger(), nullable=False),
    sa.Column('is_correct', sa.Boolean(), nullable=False),
    sa.Column('time_spent_seconds', sa.Integer(), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), server_default=sa.text("TIMEZONE('utc', now())"), nullable=False, comment='Record creation date and time'),
    sa.CheckConstraint('time_spent_seconds >= 0', name='positive_time'),
    sa.ForeignKeyConstraint(['exercise_id'], ['exercises.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_user_exercise', 'user_exercise_history', ['user_id', 'exercise_id'], unique=False)
    op.create_index('ix_user_history_completed', 'user_exercise_history', ['user_id', 'completed_at'], unique=False)
    op.create_table('user_level_languages',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False, comment='Surrogate key of the table'),
    sa.Column('user_id', sa.BigInteger(), nullable=False, comment='Reference to user'),
    sa.Column('language', sa.Enum('UK', 'EN', 'DE', name='language'), nullable=False, comment='Language code in ISO 639-1" format'),
    sa.Column('level', sa.Enum('A1', 'A2', 'B1', 'B2', 'C1', 'C2', name='language_level'), nullable=False, comment='CEFR Language levels'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text("TIMEZONE('utc', now())"), nullable=False, comment='Record creation date and time'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_user_language', 'user_level_languages', ['user_id', 'language'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_user_language', table_name='user_level_languages')
    op.drop_table('user_level_languages')
    op.drop_index('ix_user_history_completed', table_name='user_exercise_history')
    op.drop_index('ix_user_exercise', table_name='user_exercise_history')
    op.drop_table('user_exercise_history')
    op.drop_table('users')
    op.drop_index('ix_exercises_active_topic_level', table_name='exercises', postgresql_where=sa.text('is_active=true'))
    op.drop_table('exercises')
    # ### end Alembic commands ###
