"""remove is_correct column from user_exercise_history

Revision ID: bf1b5c6bd1d9
Revises: 756af3813bf4
Create Date: 2026-01-20 21:42:09.714894

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bf1b5c6bd1d9'
down_revision = '756af3813bf4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_exercise_history', 'is_correct')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_exercise_history', sa.Column('is_correct', sa.BOOLEAN(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###