"""Add unique constraint and make active_learning_language nullable
    Changes:

- Added unique constraint (user_id, language) to user_level_languages
  Ensures one user cannot have duplicate language entries

- Made User.active_learning_language_id nullable
  Solves circular FK dependency between users and user_level_languages
  Allows users to exist without active language (e.g., during onboarding)

Revision ID: f363429e20bf
Revises: 3ebb198c91e4
Create Date: 2026-01-05 19:46:52.821104

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f363429e20bf'
down_revision = '3ebb198c91e4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_user_one_active', 'user_level_languages', ['user_id', 'language'])
    op.alter_column('users', 'active_learning_language_id',
               existing_type=sa.BIGINT(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'active_learning_language_id',
               existing_type=sa.BIGINT(),
               nullable=False)
    op.drop_constraint('uq_user_one_active', 'user_level_languages', type_='unique')
    # ### end Alembic commands ###