"""
Add active learning language reference to user and rename translation fields.

- Added 'user.active_learning_language_id' as a foreign key to 'user_level_languages.id'
- Renamed fields:
    - 'correct_answer_translation' → 'question_translation'
    - 'answer_translation_language' → 'question_translation_language'


Revision ID: f4962d68824f
Revises: f47b1a71c0df
Create Date: 2025-12-23 19:25:30.451503

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f4962d68824f'
down_revision: Union[str, Sequence[str], None] = 'f47b1a71c0df'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('exercises', sa.Column('question_translation', sa.Text(), nullable=True))
    op.add_column('exercises', sa.Column('question_translation_language', sa.Enum('uk', 'en', 'de', name='language'), nullable=True, comment='Language code in ISO 639-1" format'))
    op.drop_column('exercises', 'answer_translation_language')
    op.drop_column('exercises', 'correct_answer_translation')
    op.add_column('users', sa.Column('active_learning_language_id', sa.BigInteger(), nullable=False))
    op.create_foreign_key(None, 'users', 'user_level_languages', ['active_learning_language_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_column('users', 'active_learning_language_id')
    op.add_column('exercises', sa.Column('correct_answer_translation', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('exercises', sa.Column('answer_translation_language', postgresql.ENUM('uk', 'en', 'de', name='language'), autoincrement=False, nullable=True, comment='Language code in ISO 639-1" format'))
    op.drop_column('exercises', 'question_translation_language')
    op.drop_column('exercises', 'question_translation')
    # ### end Alembic commands ###
